[package]
name = "notion_rs"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde_derive = "1.0.94"
serde_json = "1.0.40"



[dev-dependencies]


[[example]]
name = "client_test"
path = "src/examples/client_test.rs"

[[example]]
name = "page_info"
path = "src/examples/page_info.rs"
