# Make sure not to commit this file to git! your token will be exposed!
# The purpose of this file is to configure the client without env vars, useful for docker

# auth
token_v2 = "<your token goes here>"

# config
cache = true




